function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 07-Dec-2017 16:34:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Self done','LineWidth',3,'LineStyle','-.',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(plot1(2),'DisplayName','With 2 nodes in layer 1',...
    'Color',[0.635294139385223 0.0784313753247261 0.184313729405403]);
set(plot1(3),'DisplayName','With 4 nodes in layer 1',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(4),'DisplayName','With 6 nodes in layer 1');
set(plot1(5),'DisplayName','With 8 nodes in layer 1');
set(plot1(6),'DisplayName','With 10 nodes in layer 1',...
    'Color',[0.39215686917305 0.474509805440903 0.635294139385223]);
set(plot1(7),'DisplayName','Cloud with pipe width 2','LineStyle','--');
set(plot1(8),'DisplayName','Cloud with pipe width 4','LineStyle','--');
set(plot1(9),'DisplayName','Cloud with pipe width 6','LineStyle','--',...
    'Color',[0.494117647409439 0.184313729405403 0.556862771511078]);
set(plot1(10),'DisplayName','Cloud with pipe width 8','LineStyle','--',...
    'Color',[0.466666668653488 0.674509823322296 0.18823529779911]);
set(plot1(11),'DisplayName','Cloud with pipe width 10','LineStyle','--',...
    'Color',[0.39215686917305 0.474509805440903 0.635294139385223]);

% Create xlabel
xlabel('Data Size ''G'' in bytes','FontSize',14);

% Create title
title('Time vs Data Size for various computaional scenarios with C = 250*10^{10} ',...
    'FontSize',14);

% Create ylabel
ylabel('Time in seconds','FontSize',14);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'LineStyleOrderIndex',2);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.15771282919614 0.529950032712357 0.210617443349701 0.287867852151127],...
    'FontSize',10.8);

